FROM node:22.14.0-alpine3.21 as builder

WORKDIR /app

COPY ../package*.json ./
RUN npm ci

COPY . .

RUN npm run build


FROM node:22.14.0-alpine3.21

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY ../package*.json ./
RUN npm ci --only=production

ENV NODE_ENV=prod

CMD ["node", "dist/index.js"]