name: Restrict merges to main

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump PR Info
        run: |
          echo "This is a test for pull_request_target event."
          echo "Event name: ${{ github.event_name }}"
          echo "PR action: ${{ github.event.action }}"
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
